#!/usr/bin/env bash

echo 'Submit articles to Qiita!'

ITEMS_PATH=items
for FILE in `git diff origin/master --name-only --relative=$ITEMS_PATH | grep README.md` ; do
  ruby scripts/deploy.rb $FILE
  git add `dirname $ITEMS_PATH/$FILE`
done
